<a href="https://colab.research.google.com/github/MarceloPiemonteRibeiro/learning-Machine-learning/blob/main/Recommender%20system/ML_system_recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source: alur course about ML and [recommendation system](https://cursos.alura.com.br/course/introducao-a-sistemas-de-recomendacao-com-python)

# Import data

import movies from movies lems

In [1]:
import pandas as pd

filmes = pd.read_csv("movies.csv")
filmes.columns = ["filmeId", "titulo", "generos"]
filmes = filmes.set_index("filmeId")
filmes.head()

titulo  \
filmeId                                       
1                          Toy Story (1995)   
2                            Jumanji (1995)   
3                   Grumpier Old Men (1995)   
4                  Waiting to Exhale (1995)   
5        Father of the Bride Part II (1995)   

                                             generos  
filmeId                                               
1        Adventure|Animation|Children|Comedy|Fantasy  
2                         Adventure|Children|Fantasy  
3                                     Comedy|Romance  
4                               Comedy|Drama|Romance  
5                                             Comedy

import the movies' ratings

In [2]:
notas = pd.read_csv("ratings.csv")
notas.columns = ["usuarioId", "filmeId", "nota", "momento"]
notas.head()

usuarioId  filmeId  nota    momento
0          1        1   4.0  964982703
1          1        3   4.0  964981247
2          1        6   4.0  964982224
3          1       47   5.0  964983815
4          1       50   5.0  964982931

Summarize

In [3]:
notas.describe()

usuarioId        filmeId           nota       momento
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

# Setting a recommendation system

## Recommend based on popularity and items characteritics (users' gradings)

So far we have 2 databases, one about the movies and the second about the grades given by different users. The first issue is about the representativeness of the sample. The second issue is that some movies can be watched by few users and this could be accentuaded if the ratings are biased.

First, order the movies by popularity

In [4]:
total_de_votos = notas["filmeId"].value_counts()
total_de_votos.head()

356     329
318     317
296     307
593     279
2571    278
Name: filmeId, dtype: int64

Append the previous to the movies database

In [5]:
filmes['total_de_votos'] = total_de_votos
filmes.head()

titulo  \
filmeId                                       
1                          Toy Story (1995)   
2                            Jumanji (1995)   
3                   Grumpier Old Men (1995)   
4                  Waiting to Exhale (1995)   
5        Father of the Bride Part II (1995)   

                                             generos  total_de_votos  
filmeId                                                               
1        Adventure|Animation|Children|Comedy|Fantasy           215.0  
2                         Adventure|Children|Fantasy           110.0  
3                                     Comedy|Romance            52.0  
4                               Comedy|Drama|Romance             7.0  
5                                             Comedy            49.0

Thus, we are recommending below the most popular movies

In [6]:
filmes.sort_values("total_de_votos", ascending = False).head()

titulo                      generos  \
filmeId                                                                  
356                   Forrest Gump (1994)     Comedy|Drama|Romance|War   
318      Shawshank Redemption, The (1994)                  Crime|Drama   
296                   Pulp Fiction (1994)  Comedy|Crime|Drama|Thriller   
593      Silence of the Lambs, The (1991)        Crime|Horror|Thriller   
2571                   Matrix, The (1999)       Action|Sci-Fi|Thriller   

         total_de_votos  
filmeId                  
356               329.0  
318               317.0  
296               307.0  
593               279.0  
2571              278.0

Finding the average rating of the movies

In [7]:
notas_medias = notas.groupby("filmeId").mean()["nota"]
notas_medias.head()

filmeId
1    3.920930
2    3.431818
3    3.259615
4    2.357143
5    3.071429
Name: nota, dtype: float64

Append to the previous movies' database. It shows how many times people watch and graded a given movie (total_de_votos) and the last column the average grade

In [8]:
filmes["nota_media"] = notas_medias
filmes.sort_values("total_de_votos", ascending = False).head(10)

titulo  \
filmeId                                              
356                            Forrest Gump (1994)   
318               Shawshank Redemption, The (1994)   
296                            Pulp Fiction (1994)   
593               Silence of the Lambs, The (1991)   
2571                            Matrix, The (1999)   
260      Star Wars: Episode IV - A New Hope (1977)   
480                           Jurassic Park (1993)   
110                              Braveheart (1995)   
589              Terminator 2: Judgment Day (1991)   
527                        Schindler's List (1993)   

                                  generos  total_de_votos  nota_media  
filmeId                                                                
356              Comedy|Drama|Romance|War           329.0    4.164134  
318                           Crime|Drama           317.0    4.429022  
296           Comedy|Crime|Drama|Thriller           307.0    4.197068  
593                 Crime|Horror|Thriller           279.0    4.161290  
2571               Action|Sci-Fi|Thriller           278.0    4.192446  
260               Action|Adventure|Sci-Fi           251.0    4.231076  
480      Action|Adventure|Sci-Fi|Thriller           238.0    3.750000  
110                      Action|Drama|War           237.0    4.031646  
589                         Action|Sci-Fi           224.0    3.970982  
527                             Drama|War           220.0    4.225000

Instead of ordering by the total views but by tha verage grading. However, the trade-off number of views and high grades is illustrated. Below, outliers are exposed, with movies with very few views and high grades are in the top of the list.

In [9]:
filmes.sort_values("nota_media", ascending = False).head(10)

titulo                   generos  \
filmeId                                                                        
88448        Paper Birds (Pájaros de papel) (2010)              Comedy|Drama   
100556                  Act of Killing, The (2012)               Documentary   
143031                             Jump In! (2007)      Comedy|Drama|Romance   
143511                                Human (2015)               Documentary   
143559                         L.A. Slasher (2015)      Comedy|Crime|Fantasy   
6201                              Lady Jane (1986)             Drama|Romance   
102217              Bill Hicks: Revelations (1993)                    Comedy   
102084                Justice League: Doom (2012)   Action|Animation|Fantasy   
6192     Open Hearts (Elsker dig for evigt) (2002)                   Romance   
145994                      Formula of Love (1984)                    Comedy   

         total_de_votos  nota_media  
filmeId                              
88448               1.0         5.0  
100556              1.0         5.0  
143031              1.0         5.0  
143511              1.0         5.0  
143559              1.0         5.0  
6201                1.0         5.0  
102217              1.0         5.0  
102084              1.0         5.0  
6192                1.0         5.0  
145994              1.0         5.0

It is possible to filter out movies with few views (less than 50 views) instead.

In [10]:
filmes_com_mais_de_50_votos = filmes.query("total_de_votos >= 50")
filmes_com_mais_de_50_votos.sort_values("nota_media", ascending = False).head(10)

titulo  \
filmeId                                                      
318                       Shawshank Redemption, The (1994)   
858                                  Godfather, The (1972)   
2959                                     Fight Club (1999)   
1276                                 Cool Hand Luke (1967)   
750      Dr. Strangelove or: How I Learned to Stop Worr...   
904                                     Rear Window (1954)   
1221                        Godfather: Part II, The (1974)   
48516                                 Departed, The (2006)   
1213                                     Goodfellas (1990)   
912                                      Casablanca (1942)   

                             generos  total_de_votos  nota_media  
filmeId                                                           
318                      Crime|Drama           317.0    4.429022  
858                      Crime|Drama           192.0    4.289062  
2959     Action|Crime|Drama|Thriller           218.0    4.272936  
1276                           Drama            57.0    4.271930  
750                       Comedy|War            97.0    4.268041  
904                 Mystery|Thriller            84.0    4.261905  
1221                     Crime|Drama           129.0    4.259690  
48516           Crime|Drama|Thriller           107.0    4.252336  
1213                     Crime|Drama           126.0    4.250000  
912                    Drama|Romance           100.0    4.240000

## Recommend based on the user preferences/characteristics

The recommendation is based on the movies watched by the user

### Characteristics

Movies whatched by an hypothetic user

In [11]:
eu_assisti = [1, 21, 19, 10, 11, 7, 2]
filmes.loc[eu_assisti]

titulo  \
filmeId                                          
1                             Toy Story (1995)   
21                           Get Shorty (1995)   
19       Ace Ventura: When Nature Calls (1995)   
10                            GoldenEye (1995)   
11              American President, The (1995)   
7                               Sabrina (1995)   
2                               Jumanji (1995)   

                                             generos  total_de_votos  \
filmeId                                                                
1        Adventure|Animation|Children|Comedy|Fantasy           215.0   
21                             Comedy|Crime|Thriller            89.0   
19                                            Comedy            88.0   
10                         Action|Adventure|Thriller           132.0   
11                              Comedy|Drama|Romance            70.0   
7                                     Comedy|Romance            54.0   
2                         Adventure|Children|Fantasy           110.0   

         nota_media  
filmeId              
1          3.920930  
21         3.494382  
19         2.727273  
10         3.496212  
11         3.671429  
7          3.185185  
2          3.431818

**Filter movies from a given genre and with more than 50 views and excluding the ones a given user already watched**

In [12]:
aventura_infantil_e_fantasia = filmes_com_mais_de_50_votos.query("generos=='Adventure|Children|Fantasy'")
aventura_infantil_e_fantasia.drop(eu_assisti, errors='ignore').sort_values("nota_media", ascending = False).head(10)


titulo  \
filmeId                                                      
4896     Harry Potter and the Sorcerer's Stone (a.k.a. ...   
41566    Chronicles of Narnia: The Lion, the Witch and ...   

                            generos  total_de_votos  nota_media  
filmeId                                                          
4896     Adventure|Children|Fantasy           107.0    3.761682  
41566    Adventure|Children|Fantasy            62.0    3.443548

Collaborative filtering x Content based filtering. See different types and characteristics of recommender systems https://en.wikipedia.org/wiki/Recommender_system

Some systems will show you popular options, other will be based on what you have watched, or based on movies of niche (fewer views) to improve diversity, etc.

### Recommendation based on other user profiles

Now we will proceed with a recommendation based on what similar user profiles watched.
For example, for movie id=1, user A rate 6, user B rate 6.5, user C rated 6.3 while user D rate 2.5. Therefore user A,B,C form a group and user D anothe one. However, calculating the distances between the profiles when analysing more movies ids, things get trickier.

For example ratings fiven by the user=1 to all movies he/she watched

In [13]:
notas_do_usuario = notas.query("usuarioId==1")
notas_do_usuario = notas_do_usuario[["filmeId", "nota"]].set_index("filmeId")
notas_do_usuario

nota
filmeId      
1         4.0
3         4.0
6         4.0
47        5.0
50        5.0
...       ...
3744      4.0
3793      5.0
3809      4.0
4006      4.0
5060      5.0

[232 rows x 1 columns]

Genralize for all user

In [14]:
def notas_do_usuario(usuario):
  notas_do_usuario = notas.query("usuarioId==%d" % usuario)
  notas_do_usuario = notas_do_usuario[["filmeId", "nota"]].set_index("filmeId")
  return notas_do_usuario

This function alllows to see the ratings given by each user

For example user 1 and user 4

In [15]:
usuario1 = notas_do_usuario(1)
usuario4 = notas_do_usuario(4)

In [16]:
usuario1.head()

nota
filmeId      
1         4.0
3         4.0
6         4.0
47        5.0
50        5.0

To illustrate what will be done, see what movies user 1 watched, the respective grade and what user 4 also watched and graded.

In [17]:
usuario1.join(usuario4, lsuffix="_esquerda", rsuffix="_direita").dropna().head() # esquerda is user 1 and direita user 4 (added dropna to filter only movies watched by both)

nota_esquerda  nota_direita
filmeId                             
47                 5.0           2.0
235                4.0           2.0
260                5.0           5.0
296                3.0           1.0
441                4.0           1.0

Calculate the distance between the columns above 

formula to calculate distance between 2 columns

In [18]:
def distancia_de_vetores(a,b):
  return np.linalg.norm(a - b)

In [19]:
import numpy as np
diferencas = usuario1.join(usuario4, lsuffix="_esquerda", rsuffix="_direita").dropna()
distancia_de_vetores(diferencas['nota_esquerda'], diferencas['nota_direita'])

11.135528725660043

Make a function for all users

In [20]:
def distancia_de_usuarios(usuario_id1, usuario_id2):
  notas1 = notas_do_usuario(usuario_id1)
  notas2 = notas_do_usuario(usuario_id2)
  diferencas = notas1.join(notas2, lsuffix="_esquerda", rsuffix="_direita").dropna()
  distancia =  distancia_de_vetores(diferencas['nota_esquerda'], diferencas['nota_direita'])
  return [usuario_id1, usuario_id2, distancia]

Test the ditance between users 1 and 4 again but using the function now

In [21]:
distancia_de_usuarios(1,4) # same as expected

[1, 4, 11.135528725660043]

Imagine you have an hypothetical user and we need to find the profiles similar to this one to suggest a movie given the profiles' similarities.

In [22]:
# number of users
quantidade_de_usuarios = len(notas['usuarioId'].unique())
print("Temos %d usuarios" % quantidade_de_usuarios)

Temos 610 usuarios


Calculate the distance between the hypothetical user and all the others:

In [23]:
voce_id=1

for usuario_id in notas['usuarioId'].unique():
    informacoes = distancia_de_usuarios(voce_id, usuario_id)
    print(informacoes)

[1, 1, 0.0]
[1, 2, 1.4142135623730951]
[1, 3, 8.200609733428363]
[1, 4, 11.135528725660043]
[1, 5, 3.7416573867739413]
[1, 6, 8.602325267042627]
[1, 7, 7.106335201775948]
[1, 8, 3.7416573867739413]
[1, 9, 1.0]
[1, 10, 7.858116822750856]
[1, 11, 4.242640687119285]
[1, 12, 0.7071067811865476]
[1, 13, 1.4142135623730951]
[1, 14, 5.0]
[1, 15, 5.852349955359813]
[1, 16, 7.22841614740048]
[1, 17, 4.6097722286464435]
[1, 18, 8.426149773176359]
[1, 19, 17.60681686165901]
[1, 20, 6.48074069840786]
[1, 21, 9.096702699330127]
[1, 22, 5.244044240850758]
[1, 23, 5.408326913195984]
[1, 24, 4.415880433163924]
[1, 25, 1.4142135623730951]
[1, 26, 2.23606797749979]
[1, 27, 9.219544457292887]
[1, 28, 14.882876066137216]
[1, 29, 4.55521678957215]
[1, 30, 1.8027756377319946]
[1, 31, 4.58257569495584]
[1, 32, 5.196152422706632]
[1, 33, 5.916079783099616]
[1, 34, 6.363961030678928]
[1, 35, 2.23606797749979]
[1, 36, 6.519202405202649]
[1, 37, 4.0]
[1, 38, 5.5677643628300215]
[1, 39, 11.090536506409418]
[1, 40

Create a function and show the distance between the hypothetical user 1 and 5 others

In [37]:
def distancia_de_todos(voce_id):
  todos_os_usuarios = notas['usuarioId'].unique()
  distancias = [distancia_de_usuarios(voce_id, usuario_id) for usuario_id in todos_os_usuarios]
  distancias = pd.DataFrame(distancias, columns = ["voce", "outra_pessoa", "distancia"])
  return distancias

distancia_de_todos(1).head()

voce  outra_pessoa      distancia
0     1             1       0.000000
1     1             2  100000.000000
2     1             3       8.200610
3     1             4      11.135529
4     1             5       3.741657

Some rows have 0 as distance which is weird

When used dropna previously the cases where both users did not watched a given movie were kept

In [32]:
notas_do_usuario(1).join(notas_do_usuario(1), lsuffix="_1", rsuffix="4").dropna()

nota_1  nota4
filmeId               
1           4.0    4.0
3           4.0    4.0
6           4.0    4.0
47          5.0    5.0
50          5.0    5.0
...         ...    ...
3744        4.0    4.0
3793        5.0    5.0
3809        4.0    4.0
4006        4.0    4.0
5060        5.0    5.0

[232 rows x 2 columns]

The users that have nothing in common should have a high distance between them

In [36]:
def distancia_de_usuarios(usuario_id1, usuario_id2, minimo = 5): # set min =5
  notas1 = notas_do_usuario(usuario_id1)
  notas2 = notas_do_usuario(usuario_id2)
  diferencas = notas1.join(notas2, lsuffix="_esquerda", rsuffix="_direita").dropna()
  
  if(len(diferencas) < minimo):
    return [usuario_id1, usuario_id2, 100000] # set 100000 as distance
  
  distancia =  distancia_de_vetores(diferencas['nota_esquerda'], diferencas['nota_direita'])
  return [usuario_id1, usuario_id2, distancia]

In [38]:
distancia_de_todos(1).head()

voce  outra_pessoa      distancia
0     1             1       0.000000
1     1             2  100000.000000
2     1             3       8.200610
3     1             4      11.135529
4     1             5       3.741657

In [39]:
def mais_proximos_de(voce_id):
  distancias = distancia_de_todos(voce_id)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id)
  return distancias

Order users with more and less distance than this hypothetical user. All the users that watched less than 5 movies were excluded

In [42]:
mais_proximos_de(1).head()

voce  distancia
outra_pessoa                 
77               1   0.000000
511              1   0.500000
366              1   0.707107
523              1   1.000000
49               1   1.000000

### Parameters

Define how many users will be kept to be compared

In [43]:
def mais_proximos_de(voce_id, n = None): # None= all users
  distancias = distancia_de_todos(voce_id, n = n)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id)
  return distancias

Otherwise you can select a certain number of users tom compare

In [44]:
def distancia_de_todos(voce_id, n = None):
  todos_os_usuarios = notas['usuarioId'].unique()
  if n:
    todos_os_usuarios = todos_os_usuarios[:n]
  distancias = [distancia_de_usuarios(voce_id, usuario_id) for usuario_id in todos_os_usuarios]
  distancias = pd.DataFrame(distancias, columns = ["voce", "outra_pessoa", "distancia"])
  return distancias

For example, 50

In [45]:
mais_proximos_de(1, n = 50)

voce      distancia
outra_pessoa                     
49               1       1.000000
9                1       1.000000
13               1       1.414214
25               1       1.414214
30               1       1.802776
35               1       2.236068
26               1       2.236068
46               1       3.316625
8                1       3.741657
44               1       3.741657
5                1       3.741657
37               1       4.000000
48               1       4.123106
11               1       4.242641
24               1       4.415880
29               1       4.555217
31               1       4.582576
17               1       4.609772
43               1       4.795832
14               1       5.000000
32               1       5.196152
22               1       5.244044
23               1       5.408327
38               1       5.567764
15               1       5.852350
33               1       5.916080
47               1       6.244998
34               1       6.363961
20               1       6.480741
36               1       6.519202
40               1       6.855655
7                1       7.106335
16               1       7.228416
50               1       7.331439
10               1       7.858117
3                1       8.200610
18               1       8.426150
6                1       8.602325
21               1       9.096703
27               1       9.219544
41               1      10.198039
45               1      10.653638
39               1      11.090537
4                1      11.135529
42               1      12.000000
28               1      14.882876
19               1      17.606817
2                1  100000.000000
12               1  100000.000000

You can discard users with long distances (e.g., 100.000)

In [47]:
def distancia_de_usuarios(usuario_id1, usuario_id2, minimo = 5):
  notas1 = notas_do_usuario(usuario_id1)
  notas2 = notas_do_usuario(usuario_id2)
  diferencas = notas1.join(notas2, lsuffix="_esquerda", rsuffix="_direita").dropna()
  
  if(len(diferencas) < minimo):
    return None # instead of 100.000 as done previously
  
  distancia =  distancia_de_vetores(diferencas['nota_esquerda'], diferencas['nota_direita'])
  return [usuario_id1, usuario_id2, distancia]

In [48]:
def distancia_de_todos(voce_id, numero_de_usuarios_a_analisar = None):
  todos_os_usuarios = notas['usuarioId'].unique()
  if numero_de_usuarios_a_analisar:
    todos_os_usuarios = todos_os_usuarios[:numero_de_usuarios_a_analisar]
  distancias = [distancia_de_usuarios(voce_id, usuario_id) for usuario_id in todos_os_usuarios]
  distancias = list(filter(None, distancias))
  distancias = pd.DataFrame(distancias, columns = ["voce", "outra_pessoa", "distancia"])
  return distancias

In [49]:
def mais_proximos_de(voce_id, numero_de_usuarios_a_analisar = None):
  distancias = distancia_de_todos(voce_id, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id)
  return distancias

In [50]:
mais_proximos_de(1, numero_de_usuarios_a_analisar = 50)

voce  distancia
outra_pessoa                 
49               1   1.000000
9                1   1.000000
25               1   1.414214
13               1   1.414214
30               1   1.802776
35               1   2.236068
26               1   2.236068
46               1   3.316625
8                1   3.741657
5                1   3.741657
44               1   3.741657
37               1   4.000000
48               1   4.123106
11               1   4.242641
24               1   4.415880
29               1   4.555217
31               1   4.582576
17               1   4.609772
43               1   4.795832
14               1   5.000000
32               1   5.196152
22               1   5.244044
23               1   5.408327
38               1   5.567764
15               1   5.852350
33               1   5.916080
47               1   6.244998
34               1   6.363961
20               1   6.480741
36               1   6.519202
40               1   6.855655
7                1   7.106335
16               1   7.228416
50               1   7.331439
10               1   7.858117
3                1   8.200610
18               1   8.426150
6                1   8.602325
21               1   9.096703
27               1   9.219544
41               1  10.198039
45               1  10.653638
39               1  11.090537
4                1  11.135529
42               1  12.000000
28               1  14.882876
19               1  17.606817

See the most similar users and recommend the best movies to the hypothetical user except what he/she has already watched.

In [51]:
def sugere_para(voce, numero_de_usuarios_a_analisar = None):
  notas_de_voce = notas_do_usuario(voce)
  filmes_que_voce_ja_viu = notas_de_voce.index

  similares = mais_proximos_de(voce, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  similar = similares.iloc[0].name
  notas_do_similar = notas_do_usuario(similar)
  notas_do_similar = notas_do_similar.drop(filmes_que_voce_ja_viu, errors='ignore')
  recomendacoes = notas_do_similar.sort_values("nota", ascending=False)
  return recomendacoes.join(filmes)

In [52]:
sugere_para(1, numero_de_usuarios_a_analisar=50).head()

nota                            titulo  \
filmeId                                           
1200      4.5                     Aliens (1986)   
4022      4.5                  Cast Away (2000)   
47099     4.5  Pursuit of Happyness, The (2006)   
79132     4.5                  Inception (2010)   
109487    4.5               Interstellar (2014)   

                                                 generos  total_de_votos  \
filmeId                                                                    
1200                      Action|Adventure|Horror|Sci-Fi           126.0   
4022                                               Drama           100.0   
47099                                              Drama            46.0   
79132    Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX           143.0   
109487                                       Sci-Fi|IMAX            73.0   

         nota_media  
filmeId              
1200       3.964286  
4022       3.700000  
47099      3.793478  
79132      4.066434  
109487     3.993151

Above the recommendation was done based on the most 50 similar users behaviour. Below you consider all of the users instead.

In [53]:
sugere_para(1).head()

nota                                             titulo  \
filmeId                                                            
8636      5.0                                Spider-Man 2 (2004)   
58559     5.0                            Dark Knight, The (2008)   
33794     5.0                               Batman Begins (2005)   
4993      5.0  Lord of the Rings: The Fellowship of the Ring,...   
5349      5.0                                  Spider-Man (2002)   

                                  generos  total_de_votos  nota_media  
filmeId                                                                
8636         Action|Adventure|Sci-Fi|IMAX            79.0    3.803797  
58559             Action|Crime|Drama|IMAX           149.0    4.238255  
33794                   Action|Crime|IMAX           116.0    3.862069  
4993                    Adventure|Fantasy           198.0    4.106061  
5349     Action|Adventure|Sci-Fi|Thriller           122.0    3.540984

### Recommend based on several users

So far we recommended movies considering the similarity of profiles of 1 hypothetical users and the others of the database. We now consider more than 1 user but n similar users to this hypothetical one.

Let's say the n=10 users similar to the hypothetical one

In [54]:
def mais_proximos_de(voce_id, n_mais_proximos=10, numero_de_usuarios_a_analisar = None):
  distancias = distancia_de_todos(voce_id, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id)
  return distancias.head(n_mais_proximos)

In [56]:
mais_proximos_de(1, n_mais_proximos = 10, numero_de_usuarios_a_analisar=300)


voce  distancia
outra_pessoa                 
77               1   0.000000
258              1   1.000000
49               1   1.000000
9                1   1.000000
65               1   1.322876
162              1   1.414214
90               1   1.414214
25               1   1.414214
13               1   1.414214
300              1   1.500000

In [57]:
def sugere_para(voce, n_mais_proximos = 10, numero_de_usuarios_a_analisar = None):
  notas_de_voce = notas_do_usuario(voce)
  filmes_que_voce_ja_viu = notas_de_voce.index

  similares = mais_proximos_de(voce, n_mais_proximos = n_mais_proximos, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  usuarios_similares = similares.index
  notas_dos_similares = notas.set_index("usuarioId").loc[usuarios_similares]
  recomendacoes = notas_dos_similares.groupby("filmeId").mean()[["nota"]]
  recomendacoes = recomendacoes.sort_values("nota", ascending=False)
  return recomendacoes.join(filmes)

See that above using just one hypothetical user to compare we had movies with few views being recommended. See below that recommendations have more views.

In [58]:
mais_proximos_de(1, n_mais_proximos = 2, numero_de_usuarios_a_analisar=300)


voce  distancia
outra_pessoa                 
77               1        0.0
258              1        1.0

In [63]:
def sugere_para(voce, n_mais_proximos = 10, numero_de_usuarios_a_analisar = None):
  notas_de_voce = notas_do_usuario(voce)
  filmes_que_voce_ja_viu = notas_de_voce.index

  similares = mais_proximos_de(voce, n_mais_proximos = n_mais_proximos, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  usuarios_similares = similares.index
  notas_dos_similares = notas.set_index("usuarioId").loc[usuarios_similares]
  recomendacoes = notas_dos_similares.groupby("filmeId").mean()[["nota"]]
  recomendacoes = recomendacoes.sort_values("nota", ascending=False)
  return recomendacoes.join(filmes)

In [64]:
sugere_para(1, numero_de_usuarios_a_analisar = 50).head()

nota                                             titulo  \
filmeId                                                            
187593    5.0                                  Deadpool 2 (2018)   
68157     5.0                        Inglourious Basterds (2009)   
475       5.0                   In the Name of the Father (1993)   
33794     5.0                               Batman Begins (2005)   
7153      5.0  Lord of the Rings: The Return of the King, The...   

                                generos  total_de_votos  nota_media  
filmeId                                                              
187593             Action|Comedy|Sci-Fi            12.0    3.875000  
68157                  Action|Drama|War            88.0    4.136364  
475                               Drama            25.0    4.300000  
33794                 Action|Crime|IMAX           116.0    3.862069  
7153     Action|Adventure|Drama|Fantasy           185.0    4.118919

In [65]:
sugere_para(1, numero_de_usuarios_a_analisar = 300).head()


nota                                          titulo  \
filmeId                                                         
187593    5.0                               Deadpool 2 (2018)   
802       5.0                               Phenomenon (1996)   
534       5.0                              Shadowlands (1993)   
1172      5.0  Cinema Paradiso (Nuovo cinema Paradiso) (1989)   
515       5.0                  Remains of the Day, The (1993)   

                      generos  total_de_votos  nota_media  
filmeId                                                    
187593   Action|Comedy|Sci-Fi            12.0    3.875000  
802             Drama|Romance            46.0    3.336957  
534             Drama|Romance            14.0    3.607143  
1172                    Drama            34.0    4.161765  
515             Drama|Romance            24.0    3.604167

In [66]:
sugere_para(1).head()

nota                                             titulo  \
filmeId                                                            
1704      5.0                           Good Will Hunting (1997)   
57504     5.0  Girl Who Leapt Through Time, The (Toki o kaker...   
38304     5.0                No Direction Home: Bob Dylan (2005)   
48394     5.0   Pan's Labyrinth (Laberinto del fauno, El) (2006)   
2300      5.0                              Producers, The (1968)   

                                       generos  total_de_votos  nota_media  
filmeId                                                                     
1704                             Drama|Romance           141.0    4.078014  
57504    Animation|Comedy|Drama|Romance|Sci-Fi            10.0    4.100000  
38304                              Documentary             4.0    4.625000  
48394                   Drama|Fantasy|Thriller            81.0    3.814815  
2300                                    Comedy            33.0    3.969697

You can define the most similar users using a Knn algorithm

In [67]:
def knn(voce_id, k_mais_proximos=10, numero_de_usuarios_a_analisar = None):
  distancias = distancia_de_todos(voce_id, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id)
  return distancias.head(k_mais_proximos)

In [68]:
def sugere_para(voce, k_mais_proximos = 10, numero_de_usuarios_a_analisar = None):
  notas_de_voce = notas_do_usuario(voce)
  filmes_que_voce_ja_viu = notas_de_voce.index

  similares = knn(voce, k_mais_proximos = k_mais_proximos, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  usuarios_similares = similares.index
  notas_dos_similares = notas.set_index("usuarioId").loc[usuarios_similares]
  recomendacoes = notas_dos_similares.groupby("filmeId").mean()[["nota"]]
  recomendacoes = recomendacoes.sort_values("nota", ascending=False)
  return recomendacoes.join(filmes)

In [69]:
sugere_para(1).head()

nota                                             titulo  \
filmeId                                                            
1704      5.0                           Good Will Hunting (1997)   
57504     5.0  Girl Who Leapt Through Time, The (Toki o kaker...   
38304     5.0                No Direction Home: Bob Dylan (2005)   
48394     5.0   Pan's Labyrinth (Laberinto del fauno, El) (2006)   
2300      5.0                              Producers, The (1968)   

                                       generos  total_de_votos  nota_media  
filmeId                                                                     
1704                             Drama|Romance           141.0    4.078014  
57504    Animation|Comedy|Drama|Romance|Sci-Fi            10.0    4.100000  
38304                              Documentary             4.0    4.625000  
48394                   Drama|Fantasy|Thriller            81.0    3.814815  
2300                                    Comedy            33.0    3.969697

## Test a new user

Create a new user

In [70]:
filmes.loc[[122904, 1246, 2529, 2329 , 2324 , 1 , 7 , 2 ,1196, 260]]


titulo  \
filmeId                                                      
122904                                     Deadpool (2016)   
1246                             Dead Poets Society (1989)   
2529                             Planet of the Apes (1968)   
2329                             American History X (1998)   
2324            Life Is Beautiful (La Vita è bella) (1997)   
1                                         Toy Story (1995)   
7                                           Sabrina (1995)   
2                                           Jumanji (1995)   
1196     Star Wars: Episode V - The Empire Strikes Back...   
260              Star Wars: Episode IV - A New Hope (1977)   

                                             generos  total_de_votos  \
filmeId                                                                
122904                Action|Adventure|Comedy|Sci-Fi            54.0   
1246                                           Drama            86.0   
2529                             Action|Drama|Sci-Fi            56.0   
2329                                     Crime|Drama           129.0   
2324                        Comedy|Drama|Romance|War            88.0   
1        Adventure|Animation|Children|Comedy|Fantasy           215.0   
7                                     Comedy|Romance            54.0   
2                         Adventure|Children|Fantasy           110.0   
1196                         Action|Adventure|Sci-Fi           211.0   
260                          Action|Adventure|Sci-Fi           251.0   

         nota_media  
filmeId              
122904     3.833333  
1246       3.959302  
2529       3.803571  
2329       4.217054  
2324       4.147727  
1          3.920930  
7          3.185185  
2          3.431818  
1196       4.215640  
260        4.231076

In [71]:
def novo_usuario(dados):
  novo_usuario = notas['usuarioId'].max()+1 # define the id of the new user
  notas_do_usuario_novo = pd.DataFrame(dados, columns=["filmeId", "nota"])
  notas_do_usuario_novo['usuarioId'] = novo_usuario
  return pd.concat([notas, notas_do_usuario_novo]) # add the new user to my previous df

In [72]:
notas = novo_usuario([[122904,2],[1246,5],[2529,2],[2329,5],[2324,5],[1,2],[7,0.5],[2,2],[1196,1],[260,1]])
notas.tail()

usuarioId  filmeId  nota  momento
5        611        1   2.0      NaN
6        611        7   0.5      NaN
7        611        2   2.0      NaN
8        611     1196   1.0      NaN
9        611      260   1.0      NaN

Make a recommendation for our newly created user 611

In [74]:
sugere_para(611).head()

nota                                             titulo  \
filmeId                                                            
171495    5.0                                             Cosmos   
81847     5.0                                     Tangled (2010)   
1873      5.0                             Misérables, Les (1998)   
8014      5.0  Spring, Summer, Fall, Winter... and Spring (Bo...   
103141    5.0                         Monsters University (2013)   

                                                   generos  total_de_votos  \
filmeId                                                                      
171495                                  (no genres listed)             2.0   
81847    Animation|Children|Comedy|Fantasy|Musical|Roma...            24.0   
1873                               Crime|Drama|Romance|War            10.0   
8014                                                 Drama            10.0   
103141                          Adventure|Animation|Comedy            16.0   

         nota_media  
filmeId              
171495     4.500000  
81847      3.916667  
1873       3.750000  
8014       4.250000  
103141     3.875000

We have forgotten to exclude recommendations of movies not popular (so we set views min> 50 or other number - you could focus on recommendations in movies with few views)

In [75]:
notas = notas.set_index("filmeId").loc[filmes_com_mais_de_50_votos.index]
notas.head()

usuarioId  nota       momento
filmeId                               
1                1   4.0  9.649827e+08
1                5   4.0  8.474350e+08
1                7   4.5  1.106636e+09
1               15   2.5  1.510578e+09
1               17   4.5  1.305696e+09

In [76]:
notas = notas.reset_index()
notas.head()

filmeId  usuarioId  nota       momento
0        1          1   4.0  9.649827e+08
1        1          5   4.0  8.474350e+08
2        1          7   4.5  1.106636e+09
3        1         15   2.5  1.510578e+09
4        1         17   4.5  1.305696e+09

See below the new suggestions

In [77]:
sugere_para(611).head()

nota                          titulo  \
filmeId                                             
112852   5.000000  Guardians of the Galaxy (2014)   
74458    4.750000           Shutter Island (2010)   
71535    4.666667               Zombieland (2009)   
78499    4.500000              Toy Story 3 (2010)   
2804     4.500000       Christmas Story, A (1983)   

                                                  generos  total_de_votos  \
filmeId                                                                     
112852                            Action|Adventure|Sci-Fi            59.0   
74458                              Drama|Mystery|Thriller            67.0   
71535                                Action|Comedy|Horror            53.0   
78499    Adventure|Animation|Children|Comedy|Fantasy|IMAX            55.0   
2804                                      Children|Comedy            55.0   

         nota_media  
filmeId              
112852     4.050847  
74458      4.022388  
71535      3.877358  
78499      4.109091  
2804       3.972727

When using Knn we take the average of a group of users to back the recommendation. However if only one of this group of users watched a given movie and gave a high rating this can be misleading. You can set a minimun number of views that this group needs to rate to have it recommended/considered.

In [78]:
def sugere_para(voce, k_mais_proximos = 10, numero_de_usuarios_a_analisar = None):
  notas_de_voce = notas_do_usuario(voce)
  filmes_que_voce_ja_viu = notas_de_voce.index

  similares = knn(voce, k_mais_proximos = k_mais_proximos, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  usuarios_similares = similares.index
  notas_dos_similares = notas.set_index("usuarioId").loc[usuarios_similares]
  recomendacoes = notas_dos_similares.groupby("filmeId").mean()[["nota"]] # take the average of this k group
  aparicoes = notas_dos_similares.groupby("filmeId").count()[['nota']] # count how many watched the movie
  
  filtro_minimo = k_mais_proximos / 2 # min number of people from the k group that need to watch the movie to have it recommended. Given the k_mais_proximos=10, here you say that at least 5 people among them need to watch the recommended movie
  recomendacoes = recomendacoes.join(aparicoes, lsuffix="_media_dos_usuarios", rsuffix="_aparicoes_nos_usuarios")
  recomendacoes = recomendacoes.query("nota_aparicoes_nos_usuarios >= %.2f" % filtro_minimo)  
  recomendacoes = recomendacoes.sort_values("nota_media_dos_usuarios", ascending=False)
  recomendacoes = recomendacoes.drop(filmes_que_voce_ja_viu,errors='ignore')
  return recomendacoes.join(filmes)

In [79]:
def knn(voce_id, k_mais_proximos=10, numero_de_usuarios_a_analisar = None):
  distancias = distancia_de_todos(voce_id, numero_de_usuarios_a_analisar = numero_de_usuarios_a_analisar)
  distancias = distancias.sort_values("distancia")
  distancias = distancias.set_index("outra_pessoa").drop(voce_id, errors='ignore')
  return distancias.head(k_mais_proximos)

In [82]:
sugere_para(1, numero_de_usuarios_a_analisar=300)

nota_media_dos_usuarios  nota_aparicoes_nos_usuarios  \
filmeId                                                         
318                     4.900000                            5   
4993                    4.416667                            6   
5952                    4.416667                            6   
7153                    4.416667                            6   

                                                    titulo  \
filmeId                                                      
318                       Shawshank Redemption, The (1994)   
4993     Lord of the Rings: The Fellowship of the Ring,...   
5952         Lord of the Rings: The Two Towers, The (2002)   
7153     Lord of the Rings: The Return of the King, The...   

                                generos  total_de_votos  nota_media  
filmeId                                                              
318                         Crime|Drama           317.0    4.429022  
4993                  Adventure|Fantasy           198.0    4.106061  
5952                  Adventure|Fantasy           188.0    4.021277  
7153     Action|Adventure|Drama|Fantasy           185.0    4.118919

In [83]:
sugere_para(611).head(10)

nota_media_dos_usuarios  nota_aparicoes_nos_usuarios  \
filmeId                                                         
318                     4.500000                            8   
919                     4.400000                            5   
79132                   4.357143                            7   
356                     4.350000                           10   
7361                    4.312500                            8   
904                     4.300000                            5   
593                     4.222222                            9   
46578                   4.214286                            7   
4246                    4.200000                            5   
4011                    4.200000                            5   

                                               titulo  \
filmeId                                                 
318                  Shawshank Redemption, The (1994)   
919                          Wizard of Oz, The (1939)   
79132                                Inception (2010)   
356                               Forrest Gump (1994)   
7361     Eternal Sunshine of the Spotless Mind (2004)   
904                                Rear Window (1954)   
593                  Silence of the Lambs, The (1991)   
46578                     Little Miss Sunshine (2006)   
4246                     Bridget Jones's Diary (2001)   
4011                                    Snatch (2000)   

                                                 generos  total_de_votos  \
filmeId                                                                    
318                                          Crime|Drama           317.0   
919                   Adventure|Children|Fantasy|Musical            92.0   
79132    Action|Crime|Drama|Mystery|Sci-Fi|Thriller|IMAX           143.0   
356                             Comedy|Drama|Romance|War           329.0   
7361                                Drama|Romance|Sci-Fi           131.0   
904                                     Mystery|Thriller            84.0   
593                                Crime|Horror|Thriller           279.0   
46578                             Adventure|Comedy|Drama            77.0   
4246                                Comedy|Drama|Romance            65.0   
4011                               Comedy|Crime|Thriller            93.0   

         nota_media  
filmeId              
318        4.429022  
919        3.880435  
79132      4.066434  
356        4.164134  
7361       4.160305  
904        4.261905  
593        4.161290  
46578      3.883117  
4246       3.623077  
4011       4.155914

In [84]:
sugere_para(611, k_mais_proximos=20).head(10)


nota_media_dos_usuarios  nota_aparicoes_nos_usuarios  \
filmeId                                                         
593                     4.266667                           15   
296                     4.264706                           17   
4973                    4.192308                           13   
318                     4.176471                           17   
46578                   4.150000                           10   
590                     4.136364                           11   
7361                    4.133333                           15   
4878                    4.125000                           12   
1213                    4.100000                           10   
5618                    4.100000                           10   

                                                    titulo  \
filmeId                                                      
593                       Silence of the Lambs, The (1991)   
296                                    Pulp Fiction (1994)   
4973     Amelie (Fabuleux destin d'Amélie Poulain, Le) ...   
318                       Shawshank Redemption, The (1994)   
46578                          Little Miss Sunshine (2006)   
590                              Dances with Wolves (1990)   
7361          Eternal Sunshine of the Spotless Mind (2004)   
4878                                   Donnie Darko (2001)   
1213                                     Goodfellas (1990)   
5618     Spirited Away (Sen to Chihiro no kamikakushi) ...   

                               generos  total_de_votos  nota_media  
filmeId                                                             
593              Crime|Horror|Thriller           279.0    4.161290  
296        Comedy|Crime|Drama|Thriller           307.0    4.197068  
4973                    Comedy|Romance           120.0    4.183333  
318                        Crime|Drama           317.0    4.429022  
46578           Adventure|Comedy|Drama            77.0    3.883117  
590            Adventure|Drama|Western           164.0    3.835366  
7361              Drama|Romance|Sci-Fi           131.0    4.160305  
4878     Drama|Mystery|Sci-Fi|Thriller           109.0    3.981651  
1213                       Crime|Drama           126.0    4.250000  
5618       Adventure|Animation|Fantasy            87.0    4.155172